<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2ufdok\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2ufdok/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerX2ufdok.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerX2ufdok\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerX2ufdok\appProdProjectContainer([
    'container.build_hash' => 'X2ufdok',
    'container.build_id' => '1b6991ff',
    'container.build_time' => 1602251497,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2ufdok');
