<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8duu4b\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8duu4b/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerY8duu4b.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerY8duu4b\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerY8duu4b\appProdProjectContainer([
    'container.build_hash' => 'Y8duu4b',
    'container.build_id' => '0a65e534',
    'container.build_time' => 1602685113,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY8duu4b');
